/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import * as THREE from 'three';

import { useGLTF } from '@react-three/drei';
import { useFrame, useLoader, useStore, useThree } from '@react-three/fiber';

export default function Desk({ ...props }) {
  const page = useStore((state) => state.page);
  const home = useStore((state) => state.home); 
  const animationOne = useStore((state) => state.animationOne); 

  const group = useRef();


  const { nodes, materials } = useGLTF('/desk/desk.glb');

  const texture = useLoader(THREE.TextureLoader, '/desk/bakin.jpg');
  texture.flipY = false;

  const drawerVec = new THREE.Vector3()

  useFrame(() => {
    const step = 0.05
    if(page > 0  && page < 2) {
      drawerVec.set(0, 20, -1)
      group.current.position.lerp(drawerVec, step)
    }
  });

  return (
    <group 
      ref={group}
      scale={0.25} 
      position={[0, -10, 0]}
      dispose={null}
    >
      <mesh 
        geometry={nodes.Cube.geometry} 
        // material={nodes.Cube.material} 
        position={[2.31, 3.74, 2.87]} 
        rotation={[-Math.PI, -0.64, -Math.PI]} 
        scale={[3.38, 0.29, 2.03]} 
      >
        <meshBasicMaterial 
          map={texture}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/desk/desk.glb');
